server:
  port: 8002
spring:
  application:
    name: s-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
#当使用zuul进行请求(携带cookie)
zuul:
  sensitive-headers:

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000